service: default
runtime: python38

env_variables:
  TMPDIR: "/tmp"
  CLOUD_SQL_USERNAME: ***
  CLOUD_SQL_PASSWORD: ***
  CLOUD_SQL_DATABASE_NAME: 'ocean-plastics'
  CLOUD_SQL_CONNECTION_NAME: ***

#automatic_scaling:

default_expiration: "1d"

inbound_services:
- warmup

handlers:
- url: /_ah/warmup
  script: main.py

entrypoint: gunicorn -b :$PORT main:server
