service: default
runtime: python38

env_variables:
  TMPDIR: "/tmp"
  CLOUD_SQL_USERNAME: beachclean-bay-db
  CLOUD_SQL_PASSWORD: MOhvdpf5PAnfrjbg
  CLOUD_SQL_DATABASE_NAME: ocean-plastics
  CLOUD_SQL_CONNECTION_NAME: light-team-340714:europe-west2:beachclean-bay-db

#automatic_scaling:

default_expiration: "1d"

inbound_services:
- warmup

handlers:
- url: /_ah/warmup
  script: main.py

instance_class: F1

entrypoint: gunicorn -b :$PORT main:server
